spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://sh-cynosdbmysql-grp-622vdsnq.sql.tencentcdb.com:25615/user_center'
    username: XXXXX
    password: XXXXX
  # session 的生效时间
  session:
    timeout: 86400
